apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deployment
  labels:
    team: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw-deployment
  template:
    metadata:
      labels:
        app: hw-deployment
    spec:
      containers:
      - name: app
        image: httpd:alpine3.14
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
